-- Custom migration: pgvector extension, updated_at triggers, and FTS index
-- These cannot be generated by drizzle-kit and must be applied manually or via a custom migration script.

-- 1. Enable pgvector extension (must run as superuser or pg_extension owner)
CREATE EXTENSION IF NOT EXISTS vector;

-- 2. HNSW index for captures.embedding (vector similarity search)
-- Requires pgvector >= 0.5.0
CREATE INDEX IF NOT EXISTS captures_embedding_hnsw_idx
  ON captures USING hnsw (embedding vector_cosine_ops)
  WITH (m = 16, ef_construction = 64);

-- 3. HNSW index for triggers.embedding
CREATE INDEX IF NOT EXISTS triggers_embedding_hnsw_idx
  ON triggers USING hnsw (embedding vector_cosine_ops)
  WITH (m = 16, ef_construction = 64);

-- 4. Full-text search GIN index on captures.content
CREATE INDEX IF NOT EXISTS captures_content_fts_idx
  ON captures USING gin (to_tsvector('english', content));

-- 5. set_updated_at() trigger function
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 6. Apply updated_at triggers to all tables with updated_at column
CREATE TRIGGER set_captures_updated_at
  BEFORE UPDATE ON captures
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER set_entities_updated_at
  BEFORE UPDATE ON entities
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER set_sessions_updated_at
  BEFORE UPDATE ON sessions
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER set_bets_updated_at
  BEFORE UPDATE ON bets
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER set_triggers_updated_at
  BEFORE UPDATE ON triggers
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();
