import { readFileSync, existsSync } from 'node:fs'
import { join } from 'node:path'
import type { WeeklyBriefOutput } from './weekly-brief-query.js'

// ============================================================
// HTML rendering
// ============================================================

/**
 * Renders the weekly brief HTML email body.
 *
 * Uses the weekly-brief.html template (simple string interpolation since it's
 * a static file — no Handlebars dependency). The template uses {{var}} placeholders
 * for simple strings and conditional/loop sections are handled by string construction.
 */
export function renderEmailHtml(
  brief: WeeklyBriefOutput,
  capturesByView: Record<string, number>,
  weekStart: string,
  weekEnd: string,
  captureCount: number,
): string {
  const templatePath = join(
    process.cwd(),
    'packages',
    'workers',
    'src',
    'templates',
    'weekly-brief.html',
  )

  let html: string
  try {
    html = readFileSync(templatePath, 'utf8')
  } catch {
    // Fallback to adjacent path (when run from workers package dir)
    const altPath = join(process.cwd(), 'src', 'templates', 'weekly-brief.html')
    html = existsSync(altPath)
      ? readFileSync(altPath, 'utf8')
      : buildFallbackHtml(brief, weekStart, weekEnd, captureCount)
  }

  // Replace simple {{var}} placeholders
  html = html.replaceAll('{{headline}}', escapeHtml(brief.headline))
  html = html.replaceAll('{{week_start}}', escapeHtml(weekStart))
  html = html.replaceAll('{{week_end}}', escapeHtml(weekEnd))

  const viewsSummary = Object.entries(capturesByView)
    .map(([v, n]) => `${n} ${v}`)
    .join(', ')
  html = html.replaceAll('{{captures_count}}', String(captureCount))
  html = html.replaceAll('{{brain_views_summary}}', escapeHtml(viewsSummary))

  // Handlebars-style conditional/loop blocks — manual expansion
  html = expandHtmlSection(html, 'wins', brief.wins)
  html = expandHtmlSection(html, 'blockers', brief.blockers)
  html = expandHtmlSection(html, 'risks', brief.risks)
  html = expandHtmlSection(html, 'open_loops', brief.open_loops)
  html = expandHtmlSection(html, 'next_week_focus', brief.next_week_focus)
  html = expandHtmlSection(html, 'avoided_decisions', brief.avoided_decisions)
  html = expandHtmlSection(html, 'drift_alerts', brief.drift_alerts)
  html = expandHtmlSection(html, 'connections', brief.connections)

  return html
}

// ============================================================
// Plain-text rendering
// ============================================================

/**
 * Renders the plain-text email fallback.
 */
export function renderEmailText(
  brief: WeeklyBriefOutput,
  weekStart: string,
  weekEnd: string,
  captureCount: number,
): string {
  const lines: string[] = [
    `OPEN BRAIN — WEEKLY BRIEF`,
    `Week of ${weekStart} to ${weekEnd}`,
    `${captureCount} captures`,
    '',
    `HEADLINE`,
    brief.headline,
    '',
  ]

  const sections: Array<{ title: string; items: string[] }> = [
    { title: 'WINS', items: brief.wins },
    { title: 'BLOCKERS', items: brief.blockers },
    { title: 'RISKS', items: brief.risks },
    { title: 'OPEN LOOPS', items: brief.open_loops },
    { title: 'NEXT WEEK FOCUS', items: brief.next_week_focus },
    { title: 'DECISIONS AVOIDED', items: brief.avoided_decisions },
    { title: 'DRIFT ALERTS', items: brief.drift_alerts },
    { title: 'CONNECTIONS', items: brief.connections },
  ]

  for (const { title, items } of sections) {
    if (items.length > 0) {
      lines.push(title)
      for (const item of items) {
        lines.push(`  - ${item}`)
      }
      lines.push('')
    }
  }

  lines.push('Generated by Open Brain — your self-hosted AI knowledge base.')

  return lines.join('\n')
}

// ============================================================
// Brief text (for capture-back-to-brain)
// ============================================================

/**
 * Renders the brief as plain text for capture-back-to-brain and plain email.
 */
export function buildBriefText(brief: WeeklyBriefOutput, weekStart: string, weekEnd: string): string {
  const lines: string[] = [
    `Weekly Brief — ${weekStart} to ${weekEnd}`,
    '',
    brief.headline,
    '',
  ]

  const sections: Array<{ label: string; items: string[] }> = [
    { label: 'Wins', items: brief.wins },
    { label: 'Blockers', items: brief.blockers },
    { label: 'Risks', items: brief.risks },
    { label: 'Open Loops', items: brief.open_loops },
    { label: 'Next Week Focus', items: brief.next_week_focus },
    { label: 'Decisions Avoided', items: brief.avoided_decisions },
    { label: 'Drift Alerts', items: brief.drift_alerts },
    { label: 'Connections', items: brief.connections },
  ]

  for (const { label, items } of sections) {
    if (items.length > 0) {
      lines.push(`${label}:`)
      for (const item of items) lines.push(`- ${item}`)
      lines.push('')
    }
  }

  return lines.join('\n').trim()
}

// ============================================================
// HTML helpers (exported for testing)
// ============================================================

/**
 * Minimal HTML fallback when the template file cannot be found.
 */
export function buildFallbackHtml(
  brief: WeeklyBriefOutput,
  weekStart: string,
  weekEnd: string,
  captureCount: number,
): string {
  const listItems = (items: string[]) =>
    items.length > 0 ? `<ul>${items.map(i => `<li>${escapeHtml(i)}</li>`).join('')}</ul>` : ''

  return `<!DOCTYPE html>
<html><head><meta charset="UTF-8"/><title>Open Brain Weekly Brief</title></head>
<body style="font-family:sans-serif;max-width:640px;margin:auto;padding:24px">
<h1>Open Brain — Weekly Brief</h1>
<p style="color:#666">Week of ${escapeHtml(weekStart)} – ${escapeHtml(weekEnd)} &nbsp;|&nbsp; ${captureCount} captures</p>
<h2>${escapeHtml(brief.headline)}</h2>
${brief.wins.length ? `<h3>Wins</h3>${listItems(brief.wins)}` : ''}
${brief.blockers.length ? `<h3>Blockers</h3>${listItems(brief.blockers)}` : ''}
${brief.risks.length ? `<h3>Risks</h3>${listItems(brief.risks)}` : ''}
${brief.open_loops.length ? `<h3>Open Loops</h3>${listItems(brief.open_loops)}` : ''}
${brief.next_week_focus.length ? `<h3>Next Week Focus</h3>${listItems(brief.next_week_focus)}` : ''}
${brief.avoided_decisions.length ? `<h3>Decisions Avoided</h3>${listItems(brief.avoided_decisions)}` : ''}
${brief.drift_alerts.length ? `<h3>Drift Alerts</h3>${listItems(brief.drift_alerts)}` : ''}
${brief.connections.length ? `<h3>Connections</h3>${listItems(brief.connections)}` : ''}
<hr/><p style="color:#999;font-size:12px">Generated by Open Brain</p>
</body></html>`
}

export function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

/**
 * Expands {{#if field}}...{{#each field}}<li>{{this}}</li>{{/each}}...{{/if}}
 * blocks in the HTML template.
 *
 * We do minimal regex-based expansion here rather than pulling in Handlebars.
 * The template only uses these two constructs so simple regex is sufficient.
 */
export function expandHtmlSection(html: string, field: string, items: string[]): string {
  // Match: {{#if field}}...content...{{/if}}
  const ifPattern = new RegExp(
    `\\{\\{#if ${field}\\}\\}([\\s\\S]*?)\\{\\{\\/if\\}\\}`,
    'g',
  )

  if (items.length === 0) {
    // Remove the entire block
    return html.replace(ifPattern, '')
  }

  return html.replace(ifPattern, (_, blockContent: string) => {
    // Expand {{#each field}}<li>{{this}}</li>{{/each}}
    const eachPattern = new RegExp(
      `\\{\\{#each ${field}\\}\\}([\\s\\S]*?)\\{\\{\\/each\\}\\}`,
      'g',
    )
    const expanded = blockContent.replace(eachPattern, (_, itemTemplate: string) => {
      return items
        .map(item => itemTemplate.replace(/\{\{this\}\}/g, escapeHtml(item)))
        .join('')
    })
    return expanded
  })
}
